#!/bin/bash
# This script will be auto-generated by the "Save All Notes" button
# It updates tasks.json files with notes added via the web interface

echo "This script will be generated when you add notes and click 'Save All Notes'"
echo "It will contain commands to update your tasks.json files with the new notes"
