#!/usr/bin/env python3
"""Process USA spreadsheet data and create update JSON."""

import json
from pathlib import Path

# USA spreadsheet data (41 rows fetched from MCP)
USA_SHEET_DATA = [
    ["1683494533", "SMY | US | Search | Brand Exact", "65464486037", "USA - Brand", "784198246551", "Smythson of Bond Street™", "British heritage since 1887", "Shop luxury leather pieces", "Personalize your order today", "Over 135 years of expertise", "Free delivery on orders $500+", "Handcrafted in England", "Explore luxury Christmas gifts", "Shop luxury stocking fillers", "Luxury gifts for him", "Luxury gifts for her", "Gifts for the Home", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/"],
    ["1683494533", "SMY | US | Search | Brand Exact", "65464486037", "USA - Brand", "784523200052", "Smythson of Bond Street™", "British heritage since 1887", "Shop luxury leather pieces", "Personalize your order today", "Over 135 years of expertise", "Free delivery on orders $500+", "Handcrafted in England", "Explore luxury Christmas gifts", "Shop luxury stocking fillers", "Luxury gifts for him", "Luxury gifts for her", "Gifts for the Home", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/"],
    ["1683494533", "SMY | US | Search | Brand Exact", "190395845924", "USA - Brand Sale", "784539336374", "Smythson of Bond Street™", "British heritage since 1887", "Shop luxury leather pieces", "Personalize your order today", "Over 135 years of expertise", "Free delivery on orders $500+", "Handcrafted in England", "Explore luxury Christmas gifts", "Shop luxury stocking fillers", "Luxury gifts for him", "Luxury gifts for her", "Gifts for the Home", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/"],
    ["1683494533", "SMY | US | Search | Brand Exact", "190395845924", "USA - Brand Sale", "784539336377", "Smythson of Bond Street™", "British heritage since 1887", "Shop luxury leather pieces", "Personalize your order today", "Over 135 years of expertise", "Free delivery on orders $500+", "Handcrafted in England", "Explore luxury Christmas gifts", "Shop luxury stocking fillers", "Luxury gifts for him", "Luxury gifts for her", "Gifts for the Home", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/"],
    ["1602584781", "SMY | US | Search | Brand Plus", "188121956545", "UK - semi-brand - men's briefcases", "784448339422", "Smythson of Bond Street™", "Shop Smythson briefcases", "Shop luxury leather pieces", "Luxury briefcases", "Luxury gifts for him", "Luxury gifts for her", "Explore luxury Christmas gifts", "Shop luxury leather briefcases", "Timeless leather pieces", "Over 135 years of expertise", "Free delivery on orders $500+", "", "Timeless leather craftsmanship", "Crafted for modern life", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/bags/all-bags/briefcases"],
    ["1602584781", "SMY | US | Search | Brand Plus", "60484107837", "USA - semi-brand  - diaries and organisers - notebooks", "784198246689", "Luxury leather notebooks", "Shop Smythson notebooks", "Shop luxury leather pieces", "Gift of a notebook", "Luxury gifts for him", "Luxury gifts for her", "Explore luxury Christmas gifts", "Shop luxury leather notebooks", "Timeless leather pieces", "Over 135 years of expertise", "Free delivery on orders $500+", "", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/journals-and-books/notebooks/all-notebooks"],
    ["1602584781", "SMY | US | Search | Brand Plus", "152690741492", "USA - semi-brand  - diaries and organisers - planners", "784198246692", "Luxury leather planners", "Shop Smythson planners", "Shop luxury leather pieces", "Gift of a journal", "Luxury gifts for him", "Luxury gifts for her", "Explore luxury Christmas gifts", "Shop luxury leather planners", "Timeless leather pieces", "Over 135 years of expertise", "Free delivery on orders $500+", "", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/journals-and-books/notebooks/planners"],
    ["1602584781", "SMY | US | Search | Brand Plus", "60484117197", "USA - semi-brand  - diaries and organisers - travel journals", "784198246704", "Luxury leather travel journals", "Shop Smythson travel journals", "Smythson of Bond Street™", "2026 full year journals", "Luxury gifts for him", "Luxury gifts for her", "Explore luxury Christmas gifts", "Shop luxury travel journals", "Timeless leather pieces", "Over 135 years of expertise", "Free delivery on orders $500+", "", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/journals-and-books/journals/full-year-journals"],
    ["1602584781", "SMY | US | Search | Brand Plus", "177480481116", "USA - semi-brand - home - cufflink boxes - cufflink boxes", "784198246680", "Leather cufflink boxes", "Smythson of Bond Street™", "Shop luxury leather pieces", "Shop luxury cufflink boxes", "Luxury gifts for him", "Luxury gifts for her", "Explore luxury Christmas gifts", "Discover gifts for him & her", "Timeless leather craftsmanship", "Over 135 years of expertise", "Free delivery on orders $500+", "", "", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/home/accessories/watch-cufflink-boxes"],
    ["1602584781", "SMY | US | Search | Brand Plus", "177480481436", "USA - semi-brand - home - gifts", "784198246710", "Luxury gifts", "Smythson of Bond Street™", "Shop luxury leather pieces", "Shop luxury leather gifts", "Luxury gifts for him", "Luxury gifts for her", "Explore luxury Christmas gifts", "Discover Gifts For Him & Her", "Shop luxury gifts", "Over 135 years of expertise", "Free delivery on orders $500+", "", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/gifts/christmas-gifts"],
    # ... continuing with remaining 31 USA ads
]

# Add remaining USA ads data here (rows 11-41)
USA_SHEET_DATA.extend([
    ["1602584781", "SMY | US | Search | Brand Plus", "177480480716", "USA - semi-brand - home - jewellery boxes - jewellery boxes", "784198246554", "Luxury leather jewelry boxes", "Smythson of Bond Street™", "Shop luxury leather pieces", "Gifts for the home", "Luxury gifts for him", "Luxury gifts for her", "Explore luxury Christmas gifts", "Discover gifts for him & her", "Shop luxury jewelry boxes", "Over 135 years of expertise", "Free delivery on orders $500+", "", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/home/accessories/jewellery-boxes-rolls"],
    ["1602584781", "SMY | US | Search | Brand Plus", "177480481196", "USA - semi-brand - home - jewellery boxes - ring boxes", "784198246701", "Leather ring boxes", "Smythson of Bond Street™", "Shop luxury leather pieces", "Gifts for the home", "Luxury gifts for him", "Luxury gifts for her", "Explore luxury Christmas gifts", "Discover gifts for him & her", "Shop luxury ring boxes", "Over 135 years of expertise", "Free delivery on orders $500+", "", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/home/accessories/jewellery-boxes-rolls"],
    ["1602584781", "SMY | US | Search | Brand Plus", "177480480876", "USA - semi-brand - home - jewellery boxes - rolls", "784198246557", "Luxury leather jewelry rolls", "Smythson of Bond Street™", "Shop luxury leather pieces", "Gifts for the home", "Luxury gifts for him", "Luxury gifts for her", "Explore luxury Christmas gifts", "Discover gifts for him & her", "Shop luxury jewelry rolls", "Over 135 years of expertise", "Free delivery on orders $500+", "", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/home/accessories/jewellery-boxes-rolls"],
    ["1602584781", "SMY | US | Search | Brand Plus", "177480481156", "USA - semi-brand - home - jewellery boxes - trinket trays", "784198246707", "Luxury leather trinket trays", "Smythson of Bond Street™", "Shop luxury leather pieces", "Gifts for the home", "Luxury gifts for him", "Luxury gifts for her", "Explore luxury Christmas gifts", "Discover Gifts For Him & Her", "Shop luxury trinket trays", "Over 135 years of expertise", "Free delivery on orders $500+", "", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/home/accessories/jewellery-boxes-rolls"],
    ["1602584781", "SMY | US | Search | Brand Plus", "177480481356", "USA - semi-brand - home - photo albums - albums", "784198246683", "Luxury leather photo albums", "Smythson of Bond Street™", "Shop luxury leather pieces", "Gifts for the home", "Luxury gifts for him", "Luxury gifts for her", "Explore luxury Christmas gifts", "Discover Gifts For Him & Her", "Shop luxury photo albums", "Over 135 years of expertise", "Free delivery on orders $500+", "", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/home/accessories/frames-albums"],
    ["1602584781", "SMY | US | Search | Brand Plus", "177480480956", "USA - semi-brand - home - photo frames - frames", "784198246698", "Luxury leather photo frames", "Smythson of Bond Street™", "Shop luxury leather pieces", "Gifts for the home", "Luxury gifts for him", "Luxury gifts for her", "Explore luxury Christmas gifts", "Discover Gifts For Him & Her", "Shop luxury photo frames", "Over 135 years of expertise", "Free delivery on orders $500+", "", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/home/accessories/frames-albums"],
    ["1602584781", "SMY | US | Search | Brand Plus", "177480481396", "USA - semi-brand - home - watch boxes", "784198246686", "Leather watch boxes", "Smythson of Bond Street™", "Shop luxury leather pieces", "Gifts for the home", "Luxury gifts for him", "Luxury gifts for her", "Explore luxury Christmas gifts", "Discover gifts for him & her", "Shop luxury watch boxes", "Over 135 years of expertise", "Free delivery on orders $500+", "", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/home/accessories/watch-cufflink-boxes"],
    ["1602584781", "SMY | US | Search | Brand Plus", "177480480916", "USA - semi-brand - home - watch rolls - watch rolls", "784198246695", "Luxury leather jewelry rolls", "Smythson of Bond Street™", "Shop luxury leather pieces", "Gifts for the home", "Luxury gifts for him", "Luxury gifts for her", "Explore luxury Christmas gifts", "Discover gifts for him & her", "Shop luxury jewelry rolls", "Over 135 years of expertise", "Free delivery on orders $500+", "", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/home/accessories/watch-cufflink-boxes"],
    ["1602585081", "SMY | US | Search | Brand | Leather Accessories", "60484120237", "USA - semi-brand - leather accessories - Money Clip Wallets - Generic", "784326430958", "Luxury money clip wallets", "Smythson of Bond Street™", "Shop luxury leather pieces", "Luxury stocking fillers", "Luxury gifts for him", "Luxury gifts for her", "Explore luxury Christmas gifts", "Personalize your order today", "Shop luxury card cases", "Over 135 Years Of Expertise", "Free delivery on orders $500+", "", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/accessories/all-accessories"],
    ["1602585081", "SMY | US | Search | Brand | Leather Accessories", "60484119597", "USA - semi-brand - leather accessories - Wallets", "784326430967", "Luxury leather wallets", "Smythson of Bond Street™", "Shop luxury leather pieces", "Luxury stocking fillers", "Luxury gifts for him", "Luxury gifts for her", "Explore luxury Christmas gifts", "Personalize your order today", "Shop luxury leather wallets", "Over 135 Years Of Expertise", "Free delivery on orders $500+", "", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/accessories/all-accessories"],
    ["1602585081", "SMY | US | Search | Brand | Leather Accessories", "141339429018", "USA - semi-brand - leather accessories - card cases", "784326430979", "Luxury card cases", "Smythson of Bond Street™", "Shop luxury leather pieces", "Luxury stocking fillers", "Luxury gifts for him", "Luxury gifts for her", "Explore luxury Christmas gifts", "Personalize your order today", "Shop luxury card cases", "Over 135 Years Of Expertise", "Free delivery on orders $500+", "", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/accessories/all-accessories"],
    ["1602585081", "SMY | US | Search | Brand | Leather Accessories", "141339429058", "USA - semi-brand - leather accessories - card holders", "784326430970", "Luxury leather card holders", "Smythson of Bond Street™", "Shop luxury leather pieces", "Luxury stocking fillers", "Luxury gifts for him", "Luxury gifts for her", "Explore luxury Christmas gifts", "Personalize your order today", "Shop leather card holders", "Over 135 Years Of Expertise", "Free delivery on orders $500+", "", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/accessories/all-accessories"],
    ["1602585081", "SMY | US | Search | Brand | Leather Accessories", "141339429258", "USA - semi-brand - leather accessories - cosmetic cases", "784326430985", "Luxury leather cosmetic cases", "Smythson of Bond Street™", "Shop luxury leather pieces", "Luxury stocking fillers", "Luxury gifts for him", "Luxury gifts for her", "Explore luxury Christmas gifts", "Personalize your order today", "Shop leather card holders", "Over 135 Years Of Expertise", "Free delivery on orders $500+", "", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/accessories/all-accessories"],
    ["1602585081", "SMY | US | Search | Brand | Leather Accessories", "141339429298", "USA - semi-brand - leather accessories - keyrings", "784326430988", "Luxury leather keyrings", "Smythson of Bond Street™", "Shop luxury leather pieces", "Luxury stocking fillers", "Luxury gifts for him", "Luxury gifts for her", "Explore luxury Christmas gifts", "Personalize your order today", "Shop luxury leather keyrings", "Over 135 Years Of Expertise", "Free delivery on orders $500+", "", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/accessories/all-accessories"],
    ["1602585081", "SMY | US | Search | Brand | Leather Accessories", "141339428858", "USA - semi-brand - leather accessories - laptop cases", "784326430961", "Luxury leather laptop cases", "Smythson of Bond Street™", "Shop luxury leather pieces", "Luxury stocking fillers", "Luxury gifts for him", "Luxury gifts for her", "Explore luxury Christmas gifts", "Personalize your order today", "Shop leather laptop cases", "Over 135 Years Of Expertise", "Free delivery on orders $500+", "", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/accessories/all-accessories"],
    ["1602585081", "SMY | US | Search | Brand | Leather Accessories", "141339429098", "USA - semi-brand - leather accessories - luggage tags", "784326430982", "Luxury leather luggage tags", "Smythson of Bond Street™", "Shop luxury leather pieces", "Luxury stocking fillers", "Luxury gifts for him", "Luxury gifts for her", "Explore luxury Christmas gifts", "Personalize your order today", "Shop leather luggage tags", "Over 135 Years Of Expertise", "Free delivery on orders $500+", "", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/accessories/all-accessories"],
    ["1602585081", "SMY | US | Search | Brand | Leather Accessories", "188115405997", "USA - semi-brand - leather accessories - passport holder", "784326431000", "Luxury leather passport holder", "Smythson of Bond Street™", "Shop luxury leather pieces", "Luxury stocking fillers", "Luxury gifts for him", "Luxury gifts for her", "Explore luxury Christmas gifts", "Personalize your order today", "Shop leather passport holder", "Over 135 Years Of Expertise", "Free delivery on orders $500+", "", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/leather-goods/accessories/passport-covers"],
    ["1602585081", "SMY | US | Search | Brand | Leather Accessories", "141339429538", "USA - semi-brand - leather accessories - purses - coin purses", "784326430991", "Luxury leather coin purses", "Smythson of Bond Street™", "Shop luxury leather pieces", "Luxury stocking fillers", "Luxury gifts for him", "Luxury gifts for her", "Explore luxury Christmas gifts", "Personalize your order today", "Shop leather coin purses", "Over 135 Years Of Expertise", "Free delivery on orders $500+", "", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/accessories/all-accessories/purses"],
    ["1602585081", "SMY | US | Search | Brand | Leather Accessories", "141339429498", "USA - semi-brand - leather accessories - purses - pouches", "784326430973", "Luxury leather purses", "Smythson of Bond Street™", "Shop luxury leather pieces", "Luxury stocking fillers", "Luxury gifts for him", "Luxury gifts for her", "Explore luxury Christmas gifts", "Personalize your order today", "Shop luxury leather purses", "Over 135 Years Of Expertise", "Free delivery on orders $500+", "", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/accessories/all-accessories/purses"],
    ["1602585081", "SMY | US | Search | Brand | Leather Accessories", "141339429578", "USA - semi-brand - leather accessories - travel wallets", "784326430994", "Luxury leather travel wallets", "Smythson of Bond Street™", "Shop luxury leather pieces", "Luxury stocking fillers", "Luxury gifts for him", "Luxury gifts for her", "Explore luxury Christmas gifts", "Personalize your order today", "Shop luxury travel wallets", "Over 135 Years Of Expertise", "Free delivery on orders $500+", "", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/leather-goods/accessories/travel-wallets"],
    ["1602585081", "SMY | US | Search | Brand | Leather Accessories", "141339429738", "USA - semi-brand - leather accessories - travel wallets - currency cases", "784326430964", "Luxury leather currency cases", "Smythson of Bond Street™", "Shop luxury leather pieces", "Luxury stocking fillers", "Luxury gifts for him", "Luxury gifts for her", "Explore luxury Christmas gifts", "Personalize your order today", "Shop leather currency cases", "Over 135 Years Of Expertise", "Free delivery on orders $500+", "", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/leather-goods/accessories/travel-wallets"],
    ["1602585081", "SMY | US | Search | Brand | Leather Accessories", "141339429738", "USA - semi-brand - leather accessories - travel wallets - currency cases", "784523323658", "Luxury Travel wallets", "Smythson of Bond Street™", "Shop luxury leather pieces", "Luxury stocking fillers", "Luxury gifts for him", "Luxury gifts for her", "Explore luxury Christmas gifts", "Shop leather travel wallets", "Personalize your order today", "Over 135 years of expertise", "Free delivery on orders $500+", "", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/leather-goods/accessories/travel-wallets"],
    ["1602585081", "SMY | US | Search | Brand | Leather Accessories", "141339429778", "USA - semi-brand - leather accessories - washbags - washbags", "784326430997", "Luxury leather washbags", "Smythson of Bond Street™", "Shop luxury leather pieces", "Luxury stocking fillers", "Luxury gifts for him", "Luxury gifts for her", "Explore luxury Christmas gifts", "Personalize your order today", "Shop leather card holders", "Over 135 Years Of Expertise", "Free delivery on orders $500+", "", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/accessories/all-accessories"],
    ["1602585081", "SMY | US | Search | Brand | Leather Accessories", "60484113997", "USA - semi-brand - leather accessories - women purses", "784326430955", "Luxury leather purses", "Smythson of Bond Street™", "Shop luxury leather pieces", "Luxury stocking fillers", "Luxury gifts for him", "Luxury gifts for her", "Explore luxury Christmas gifts", "Personalize your order today", "Shop luxury leather purses", "Over 135 Years Of Expertise", "Free delivery on orders $500+", "", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/accessories/all-accessories"],
    ["1602585081", "SMY | US | Search | Brand | Leather Accessories", "60484114077", "USA - semi-brand - leather accessories - zip wallets", "784326430976", "Luxury leather multi-zip cases", "Smythson of Bond Street™", "Shop luxury leather pieces", "Luxury stocking fillers", "Luxury gifts for him", "Luxury gifts for her", "Explore luxury Christmas gifts", "Personalize your order today", "Shop leather multi-zip cases", "Over 135 Years Of Expertise", "Free delivery on orders $500+", "", "Timeless leather craftsmanship", "", "", "Make the ordinary extraordinary and the everyday timeless with Smythson", "A distinctly unique, extraordinary brand catering to extraordinary people since 1887", "Discover the perfect gift this Christmas. Thoughtfully made, meaningfully given", "This Christmas, celebrate the art of thoughtful gifting with Smythson", "https://www.smythson.com/us/accessories/all-accessories"],
    ["1602584829", "SMY | US | Search | Brand | Stationery", "60484091437", "USA - semi-brand - Stationery - Personalised Stationery - Generic", "781000775209", "Smythson of Bond Street™", "Bespoke luxury stationery", "Over 135 years of expertise", "Luxury paper craftsmanship", "Free delivery on orders $500+", "Discover new arrivals", "Enjoy complimentary returns", "Personalization available", "Personalize your order today", "Discover gifts for him & her", "Exclusive luxury gift wrapping", "Uncover our latest collection", "Discover timeless collections", "", "", "Discover our unique, beautifully crafted bespoke stationery.", "Design your own suite of stationery & personalize your order with our gold stamp service.", "Discover new arrivals from luxury leather stationery, accessories, bags, notebooks & more.", "Explore our bespoke stationery services for a suite that's uniquely yours.", "https://www.smythson.com/us/accessories/all-accessories"],
    ["1602584829", "SMY | US | Search | Brand | Stationery", "141109730838", "USA - semi-brand - stationery - cards - correspondence cards", "781000644181", "Smythson of Bond Street™", "Luxury correspondence cards", "Over 135 years of expertise", "Luxury paper craftsmanship", "Free delivery on orders $500+", "Discover new arrivals", "Enjoy complimentary returns", "Personalization available", "Personalize your order today", "Discover gifts for him & her", "Exclusive luxury gift wrapping", "Uncover our latest collection", "Discover timeless collections", "", "", "Discover our unique, beautifully handcrafted correspondence cards", "Design your own suite of stationery & personalize your order with our gold stamp service.", "Discover new arrivals From luxury leather stationery, accessories, bags, notebooks & more.", "Explore our bespoke stationery services for a suite that's uniquely yours.", "https://www.smythson.com/us/stationery/cards/correspondence-cards"],
    ["1602584829", "SMY | US | Search | Brand | Stationery", "141109730798", "USA - semi-brand - stationery - cards - thank you cards", "781000644178", "Smythson of Bond Street™", "Luxury thank you cards", "Over 135 years of expertise", "Luxury paper craftsmanship", "Free delivery on orders $500+", "Discover new arrivals", "Enjoy complimentary returns", "Personalization available", "Personalize your order today", "Discover gifts for him & her", "Exclusive luxury gift wrapping", "Uncover our latest collection", "Discover timeless collections", "", "", "Discover our selection of hand-crafted thank you cards", "Design your own suite of stationery & personalize your order with our gold Stamp service.", "Discover new arrivals From luxury leather stationery, accessories, bags, notebooks & more.", "Explore our bespoke stationery services for a suite that's uniquely yours.", "https://www.smythson.com/us/stationery/cards/thank-you-cards"],
    ["1602584829", "SMY | US | Search | Brand | Stationery", "141109731038", "USA - semi-brand - stationery - invitations - invitations", "781000644172", "Smythson of Bond Street™", "Luxury invitations", "Over 135 years of expertise", "Luxury paper craftsmanship", "Free delivery on orders $500+", "Discover new arrivals", "Enjoy complimentary returns", "Personalization available", "Personalize your order today", "Discover gifts for him & her", "Exclusive luxury gift wrapping", "Uncover our latest collection", "Discover timeless collections", "", "", "Whatever the occasion, discover our hand-engraved invitations", "Design your own suite of stationery & personalize your order with our gold stamp service.", "Discover new arrivals From luxury leather stationery, accessories, bags, notebooks & more.", "Explore our bespoke stationery services for a suite that's uniquely yours.", "https://www.smythson.com/us/stationery/cards/invitations"],
    ["1602584829", "SMY | US | Search | Brand | Stationery", "141109731118", "USA - semi-brand - stationery - pencils - pencil cases", "781000644175", "Smythson of Bond Street™", "Luxury leather pencil cases", "Over 135 years of expertise", "Luxury paper craftsmanship", "Free delivery on orders $500+", "Discover new arrivals", "Enjoy complimentary returns", "Personalization available", "Personalize your order today", "Discover gifts for him & her", "Exclusive luxury gift wrapping", "Uncover our latest collection", "Discover timeless collections", "", "", "Elevate your everyday with our leather pencil cases", "Design your own suite of stationery & personalize your order with our gold stamp service.", "Discover new arrivals From luxury leather stationery, accessories, bags, notebooks & more.", "Explore our bespoke stationery services for a suite that's uniquely yours.", "https://www.smythson.com/us/leather-goods/accessories/pencil-cases"],
    ["1602584829", "SMY | US | Search | Brand | Stationery", "141109731078", "USA - semi-brand - stationery - pencils - pencils", "781000644169", "Smythson of Bond Street™", "Luxury pens & pencils", "Over 135 years of expertise", "Luxury paper craftsmanship", "Free delivery on orders $500+", "Discover new arrivals", "Enjoy complimentary returns", "Personalization available", "Personalize your order today", "Discover gifts for him & her", "Exclusive luxury gift wrapping", "Uncover our latest collection", "Discover timeless collections", "", "", "From fountain & rollerball pens to our signature gold gilded pencils, shop now", "Design your own suite of stationery & personalize your order with our gold stamp service.", "Discover new arrivals From luxury leather stationery, accessories, bags, notebooks & more.", "Explore our bespoke stationery services for a suite that's uniquely yours.", "https://www.smythson.com/us/stationery/pens-pencils"],
])

def parse_row(row):
    """Parse spreadsheet row - columns 5-19 headlines, 20-23 descriptions, 24 final URL"""
    if len(row) < 25:
        return None
    
    headlines = [row[i].strip() for i in range(5, 20) if row[i] and row[i].strip()]
    descriptions = [row[i].strip() for i in range(20, 24) if row[i] and row[i].strip()]
    
    return {
        'campaign_id': row[0], 'campaign_name': row[1], 'ad_group_id': row[2],
        'ad_group_name': row[3], 'ad_id': row[4], 'headlines': headlines,
        'descriptions': descriptions, 'final_url': row[24] if len(row) > 24 else ""
    }

# Load current state
current_state_file = Path(__file__).parent.parent / 'data' / 'usa_rsa_current_state.json'
with open(current_state_file, 'r') as f:
    current_state = json.load(f)
current_by_id = {ad['ad_id']: ad for ad in current_state}

print(f"✓ Loaded {len(current_by_id)} current USA RSAs\n")

# Parse spreadsheet
spreadsheet_ads = {}
for i, row in enumerate(USA_SHEET_DATA, 1):
    parsed = parse_row(row)
    if parsed:
        spreadsheet_ads[parsed['ad_id']] = parsed
        print(f"  Row {i}: Ad {parsed['ad_id']} - {len(parsed['headlines'])} headlines, {len(parsed['descriptions'])} descriptions")

print(f"\n✓ Parsed {len(spreadsheet_ads)} ads from spreadsheet\n")

# Compare and build updates
updates = []
changes_count = 0

for ad_id, sheet_ad in spreadsheet_ads.items():
    current_ad = current_by_id.get(ad_id)
    if not current_ad:
        print(f"⚠️  Ad {ad_id} in spreadsheet but not in current state - skipping")
        continue
    
    headlines_changed = sheet_ad['headlines'] != current_ad['current_headlines']
    descriptions_changed = sheet_ad['descriptions'] != current_ad['current_descriptions']
    url_changed = sheet_ad['final_url'] != current_ad['final_url']
    
    if headlines_changed or descriptions_changed or url_changed:
        changes_count += 1
        print(f"✓ Changes for Ad {ad_id}: {current_ad['campaign_name']}")
    
    updates.append({
        'campaign_name': current_ad['campaign_name'],
        'ad_group_name': current_ad['ad_group_name'],
        'ad_id': ad_id, 'status': current_ad['status'],
        'current_headlines': current_ad['current_headlines'],
        'new_headlines': sheet_ad['headlines'],
        'current_descriptions': current_ad['current_descriptions'],
        'new_descriptions': sheet_ad['descriptions'],
        'final_url': sheet_ad['final_url']
    })

# Save
output_file = Path(__file__).parent.parent / 'data' / 'usa_rsa_updates_from_sheet.json'
with open(output_file, 'w') as f:
    json.dump(updates, f, indent=2)

print(f"\n{'='*80}")
print(f"✓ USA processing complete: {len(updates)} ads, {changes_count} with changes")
print(f"  Output: {output_file}")
print(f"{'='*80}")
