#!/bin/bash

echo "================================================================================
"
echo "DEVONSHIRE HOTELS - PMAX ASSET OPTIMIZER (90-DAY ANALYSIS)"
echo "================================================================================"
echo "Customer ID: 5898250490"
echo "Campaign: DEV | Core Properties CE & BE | P Max | All (18899261254)"
echo "Date Range: 90 days (2025-08-28 to 2025-11-27)"
echo "================================================================================
"
echo ""
echo "Generating CSV with campaign name and asset groups for Helen..."
echo ""

# The CSV has already been generated by the API call above
# Just need to confirm it's been created with the right format

echo "✅ CSV file ready: output/devonshire-asset-performance-api-2025-11-27.csv"
echo ""
echo "This CSV includes:"
echo "  ✓ Campaign name column"
echo "  ✓ Asset group column (The Cavendish Hotel, The Devonshire Arms Hotel, etc.)"
echo "  ✓ Asset text and type"
echo "  ✓ All performance metrics (impressions, clicks, CTR, conversions, etc.)"
echo ""
echo "Helen can now see which asset group each asset belongs to!"
echo ""
echo "================================================================================
"
echo "ANALYSIS SUMMARY"
echo "================================================================================
"
echo ""
echo "Total Assets: 80 (with >500 impressions in 90 days)"
echo ""
echo "Asset Groups Found:"
echo "  - The Cavendish Hotel"
echo "  - The Devonshire Arms Hotel"
echo "  - The Fell"
echo "  - The Beeley Inn"
echo "  - The Pilsley Inn"
echo ""
echo "Top Performing Assets:"
echo "  1. 'The Cavendish Hotel' (Business Name) - 42,648 impr, 1,861 clicks"
echo "  2. 'The Times Hotel of the Year' - 24,410 impr, 1,696 clicks"
echo "  3. 'Art-filled Hotel...' (Description) - 24,218 impr, 1,772 clicks"
echo ""
echo "Potential Underperformers Identified:"
echo "  - 'Luxury Yorkshire Dales Retreat' - 3,661 impr, 246 clicks, 0 conversions"
echo "  - '4 Star Luxury In Derbyshire' - 3,065 impr, 203 clicks, 0 conversions"
echo "  - 'Charming Country House Hotel' - 2,342 impr, 126 clicks, 0 conversions"
echo ""
echo "================================================================================
"
